# Generated by Django 4.2.3 on 2023-07-21 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30, unique=True)),
                ('ip', models.GenericIPAddressField(protocol='ipv6', unique=True, verbose_name='Tailnet IP')),
                ('pre_auth_key', models.CharField(max_length=48, unique=True, validators=[django.core.validators.MinLengthValidator(48)], verbose_name='Tailnet PreAuthKey')),
                ('is_registered', models.BooleanField(default=False)),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17), django.core.validators.RegexValidator(code='nomatch', message='MAC address needs to be a lower-case, colon separated MAC address', regex='^([0-9a-f]{2}[:]){5}([0-9a-f]{2})$')], verbose_name='MAC Address')),
                ('api_key', models.CharField(max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(32)], verbose_name='API Key')),
                ('test_iperf3', models.BooleanField(default=True)),
                ('test_iperf3_bandwidth', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Expected syntax: #[KMG], where # is the bandwidth limit in bits/s', regex='^\\d{1,5}[KMG]$')])),
            ],
        ),
    ]
