# Generated by Django 4.2.3 on 2023-08-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=10, unique=True)),
                ('display_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='probe',
            name='hardware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.probehardware'),
        ),
    ]
