# Generated by Django 4.2.27 on 2026-07-01 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_probe_test_blackbox_probe_test_smokeping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probe',
            name='pre_auth_key',
            field=models.CharField(max_length=88, unique=True, validators=[django.core.validators.MinLengthValidator(88)], verbose_name='Tailnet PreAuthKey'),
        ),
    ]
